on:
  push:
    branches:
      - "master"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Docker Build
        uses: docker/build-push-action@v2.7.0
        run: docker build . --file dockerfile

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: github-pages
          folder: build

        
          