on:
  push:
    branches:
      - "master"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./dockerfile

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: index.html

        
          